[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [build]
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-env"

  [plugins.inputs]
    env = { REACT_APP = "https://eccomerce-s49e.onrender.com" }
